# Generated by Django 5.0 on 2025-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('add', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Seller Registrations',
            },
        ),
    ]
