# Generated by Django 5.0 on 2025-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistration',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
