from django.urls import path
from .views import *

urlpatterns = [
    path('',index,name='index'),
    path('demo/',demo,name='demo'),
    path('first/',first,name='first'),
    path('table/',table,name='table'),
    path('store_student/',store_student,name='store_student'),
    path('register/',register,name='register'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
    #path('catpro/<int:id>',cat_pro,name='catpro'),
    path('product_detail/<int:id>',product_detail,name='product_detail'),
    #path('products/<int:id>/',product_list_by_category, name='category_products'),
    #path('category/<int:id>/', category_products, name='category_products'),
    path('category/<str:name>/', products_by_category, name='products_by_category'),
    path('checkout/',checkout,name='checkout'),
   #path('razorpay/',razorpayment,name='razorpay'),
   #path('payment_handler/',payment_handler,name='payment_handler'),
    path('wish/',wish,name='wish'),
    path('remove_wishlist/<int:pid>/', remove_wishlist, name='remove_wishlist'),
    path('remove_all_wishlist/', remove_all_wishlist, name='remove_all_wishlist'),
    path('cart_view/',cart_view,name='cart_view'),
    path('add_qty/<int:id>',add_qty,name='add_qty'),
    path('minus_qty/<int:id>',minus_qty,name='minus_qty'),
    path('remove/<int:id>',remove,name='remove'),
    path('removeall/',remove_all,name='removeall'),
    path('all_orders/',all_orders,name='all_orders'),
    path('single_invoice/',single_invoice,name='single_invoice'),
    path('download_invoice_pdf/',download_invoice_pdf,name='download_invoice_pdf'),
    path('search/', search_products, name='search_products'),
    path('contact/', contact, name='contact'),
    path('wishlist_checkout/', wishlist_checkout, name='wishlist_checkout'),
]