# Generated by Django 5.2 on 2025-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
