# Generated by Django 5.0 on 2025-05-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_order_prods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
