# Generated by Django 5.0 on 2025-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_order_pro_remove_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prods',
            field=models.ManyToManyField(blank=True, null=True, to='app1.cart'),
        ),
    ]
