# Generated by Django 5.0 on 2025-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prods',
            field=models.ManyToManyField(to='app1.cart'),
        ),
    ]
